### ISSUE TITLE
Style of paginator

### ISSUE THREAD

**Issue by anseg82** [rezaamini-ir/migrator#30]
Hi,
I'm on chrome v97.0.4692.71 and I'm using Laravel v8.79.0, Livewire 2.9.0 and migrator v1.5.2.
As you can see in the attached image, the paginator pages and arrows seem to be "unstyled": is this correct or my issue? 
If first, are you planning a new minor release to style them?
![error_on_paginators_page](https://user-images.githubusercontent.com/32097381/149748372-40957603-bc4a-4f1e-81a8-e0652bbdce0d.png)

**Comment by iamriajul** [comment]
Do we really need pagination? I guess most people will going to use it in the Local Environment only!

FYI: I'm currently managing a project which has 250+ migrations, and I use PHPStorm's database browser without pagination. and that's very usable & speedy.

Thanks.

**Comment by mdev64** [comment]
Yes, there is a issue. It can fixed by adding WithPagination trait on the 'Read.php' file (migrator/src/Http/Livewire/Migration/Read.php) 

![image](https://user-images.githubusercontent.com/33152355/150736179-b96471e5-07dc-4ce2-8946-822fb911ef11.png)

![image](https://user-images.githubusercontent.com/33152355/150736221-1485b736-c54d-4142-a49f-564de88b790b.png)

**Comment by reziamini** [comment]
Fixed!

**Comment by anseg82** [comment]
thanks for fixing; will you publish a new release soon?

**Comment by reziamini** [comment]
@anseg82 We will release a new version as soon as possible, but for now you can update using dev-master.

**Comment by anseg82** [comment]
ok, thanks for your support

Il giorno mar 25 gen 2022 alle ore 08:55 Reza Amini <
***@***.***> ha scritto:
